### PR TITLE
Sprint 2 merge

### PR DESCRIPTION
**Pull request by AleksandarGT**
Sprint 2 components merge: navbar, sensor map, widgets, graphql connection

### CODE REVIEW

**Comment by michaelbahchevanov** [comment]
As with all the other requests we have mix and matching and fixing the main codebase

**Review by michaelbahchevanov — APPROVED** [review]

**Review by BondarencoM — APPROVED** [review]

**Comment by BondarencoM** [comment]
@MolotovHammr what's wrong with the pull request?

**Review by MolotovHammr — APPROVED** [review]

**Review by MolotovHammr — APPROVED** [review]

**Comment by MolotovHammr** [comment]
Accidentally closed the request. Can't merge the pull request yet tho

**Comment by BondarencoM** [comment]
Yes we need @larsverp  and @oererenn to approve as well

**Review by oererenn — APPROVED** [review]

**Review by larsverp — APPROVED** [review]

**Pull request merged**
